name: backend
description: An empty conduit application.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^3.0.0
  cryptography: ^2.0.5
  dbcrypt: ^2.0.0
  dio: ^4.0.6
  jaguar_jwt: ^3.0.0
  mailer: ^5.0.2
  mime: ^1.0.1
  random_string: ^2.3.1
  regexed_validator: ^2.0.0+1
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^3.0.0
